name = "careneighbor-landing"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./.next/static"

[build]
command = "npm run build"
output_directory = ".next"

[build.upload]
format = "service-worker"

[vars]
NODE_VERSION = "20"

[functions]
node_compat = true
