name = "careneighbor-website"
compatibility_date = "2023-12-01"

module.exports = {
  webpack(config) {
    config.optimization.splitChunks = { chunks: 'all' };
    return config;
  },
};

# Specify the build output directory for Pages
[build]
command = "npm run build"
pages_build_output_dir = "./dist"
